export let infoFromCharacters = [
{"Id":148,"Name":"Arya Stark","IsFemale":true,"Culture":"Northmen","Titles":["Princess"],"Aliases":["Arya Horseface","Arya Underfoot","Arry","Lumpyface","Lumpyhead","Stickboy","Weasel","Nymeria","Squan","Saltb","Cat of the Canaly","Bets","The Blind Girh","The Ugly Little Girl","Mercedenl","Mercye"],"Born":"In 289 AC, at Winterfell","Died":"","Father":null,"Mother":null,"Spouse":null,"Children":[],"Allegiances":[362],"Books":[],"PovBooks":[1,2,3,5,8],"PlayedBy":["Maisie Williams"],"TvSeries":["Season 1","Season 2","Season 3","Season 4","Season 5", "Season 6"]},
{"Id":216,"Name":"Brienne of Tarth","IsFemale":true,"Culture":"","Titles":[],"Aliases":["The Maid of Tarth","Brienne the Beauty","Brienne the Blue"],"Born":"In 280 AC","Died":"","Father":null,"Mother":null,"Spouse":null,"Children":[],"Allegiances":[380,17,362],"Books":[2,3,8],"PovBooks":[5],"PlayedBy":["Gwendoline Christie"],"TvSeries":["Season 2","Season 3","Season 4","Season 5", "Season 6"]},
{"Id":271,"Name":"Daenerys Targaryen","IsFemale":true,"Culture":"","Titles":["Princess"],"Aliases":[],"Born":"In 172 AC","Died":"","Father":null,"Mother":null,"Spouse":719,"Children":[],"Allegiances":[378,285],"Books":[11,6,8],"PovBooks":[],"PlayedBy":[""],"TvSeries":[]},
{"Id":849,"Name":"Ramsay Snow","IsFemale":false,"Culture":"Northmen","Titles":["Lord of the Hornwood","Lord of Winterfell","Castellan of the Dreadfort"],"Aliases":["Ramsay Bolton","The Bastard of Bolton","The Bastard of the Dreadfort","Reek","Red Helm","Monster"],"Born":"In 282 AC or before","Died":"","Father":null,"Mother":null,"Spouse":317,"Children":[],"Allegiances":[34],"Books":[2,3,5,8],"PovBooks":[],"PlayedBy":["Iwan Rheon"],"TvSeries":["Season 3","Season 4","Season 5", "Season 6"]},
{"Id":954,"Name":"Samwell Tarly","IsFemale":false,"Culture":"Andal","Titles":[],"Aliases":["Sam","Ser Piggy","Prince Pork-chop","Lady Piggy","Sam the Slayer","Black Sam","Lord of Ham"],"Born":"In 283 AC, at Horn Hill","Died":"","Father":null,"Mother":null,"Spouse":null,"Children":[],"Allegiances":[379],"Books":[1,2,8],"PovBooks":[3,5],"PlayedBy":["John Bradley-West"],"TvSeries":["Season 1","Season 2","Season 3","Season 4","Season 5","Season 6"]},
{"Id":1052,"Name":"Tyrion Lannister","IsFemale":false,"Culture":"","Titles":["Acting Hand of the King (former)","Master of Coin (former)"],"Aliases":["The Imp","Halfman","The boyman","Giant of Lannister","Lord Tywin's Doom","Lord Tywin's Bane","Yollo","Hugor Hill","No-Nose","Freak","Dwarf"],"Born":"In 273 AC, at Casterly Rock","Died":"","Father":null,"Mother":null,"Spouse":2044,"Children":[],"Allegiances":[229],"Books":[5,11],"PovBooks":[1,2,3,8],"PlayedBy":["Peter Dinklage"],"TvSeries":["Season 1","Season 2","Season 3","Season 4","Season 5", "Season 6"]},
{"Id":2024,"Name":"Tormund","IsFemale":false,"Culture":"Free Folk","Titles":["Tall-talker","Horn-blower and Breaker of Ice","Husband to Bears","the Mead-king of Ruddy Hall","Speaker to Gods and Father of Hosts"],"Aliases":["Tormund Giantsbane","Mead-King of Ruddy Hall","Tormund Thunderfist","Tormund Horn-Blower","Tormund Tall-Talker","Breaker of Ice","Husband to Bears","Speaker to Gods","Father of Hosts"],"Born":"","Died":"","Father":null,"Mother":null,"Spouse":null,"Children":[],"Allegiances":[],"Books":[3,5,8],"PovBooks":[],"PlayedBy":["Kristofer Hivju"],"TvSeries":["Season 3","Season 4","Season 5", "Season 6"]},
]
